version: '3.8'

services:
  config-service:
    image: config-service
    ports: 
    - "8888:8888"
    network_mode: "host"
  registry-service:
    image: registry-service
    ports: 
    - "8761:8761"
    depends_on: 
    - config-service
    restart: unless-stopped
    network_mode: "host"
  gateway:
    image: gateway
    ports: 
    - "9000:9000"
    depends_on: 
    - config-service
    - registry-service
    restart: unless-stopped
    network_mode: "host"
  membre-service:
    image: membre-service
    depends_on: 
    - config-service
    - registry-service
    restart: unless-stopped
    network_mode: "host"
  publication-service:
    image: publication-service
    depends_on: 
    - config-service
    - registry-service
    restart: unless-stopped
    network_mode: "host"
  evenement-service:
    image: evenement-service
    depends_on: 
    - config-service
    - registry-service
    restart: unless-stopped
    network_mode: "host"
  outil-service:
    image: outil-service
    depends_on: 
    - config-service
    - registry-service
    restart: unless-stopped
    network_mode: "host"