version: "3.8"

services:
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  registry-service:
    image: registry-service
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    restart: unless-stopped
    networks:
      - microservices-network

  gateway:
    image: gateway
    ports:
      - "9000:9000"
    depends_on:
      - config-service
      - registry-service
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

  member-service:
    image: member-service
    depends_on:
      - config-service
      - registry-service
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab2024
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

  publication-service:
    image: publication-service
    depends_on:
      - config-service
      - registry-service
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab2024
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

  event-service:
    image: event-service
    depends_on:
      - config-service
      - registry-service
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab2024
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

  tool-service:
    image: tool-service
    depends_on:
      - config-service
      - registry-service
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab2024
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: lab2024
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  frontend:
    image: frontend
    ports:
      - "4200:4200"
    depends_on:
      - gateway
      - member-service
      - publication-service
      - event-service
      - tool-service
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - microservices-network

volumes:
  postgres-data:
    driver: local

networks:
  microservices-network:
    driver: bridge
